name: ⚒️ Build Codebase
run-name: ${{ github.actor }} is building the codebase
permissions:
  contents: read

on:
  push:
   branches-ignore:
     - main
  workflow_dispatch:
  workflow_call:
    outputs:
      app-build:
        description: "App build artifact"
        value: ${{ jobs.build-app.outputs.artifact }}

jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: semgrep/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      # Fetch project source with GitHub Actions Checkout
      - name: Checkout code
        uses: actions/checkout@v4
      # Run the "semgrep scan" command on the command line of the docker image.
      - name: Run Semgrep
        run: semgrep scan # ci
        # env:
          # Connect to Semgrep AppSec Platform through your SEMGREP_APP_TOKEN.
          # Generate a token from Semgrep AppSec Platform > Settings
          # and add it to your GitHub secrets.
          # SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  build-app:
    name: Build Application
    runs-on: ubuntu-latest
    outputs:
      artifact: app-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 23
          cache: "gradle"
          cache-dependency-path: |
            .gradle*
            ./**/gradle-wrapper.properties
      - name: Cache OWASP Dependency-Check DB
        uses: actions/cache@v4
        with:
          path: .dependency-check-data
          key: dependency-check-db-${{ runner.os }}

      - name: Build Server
        run: ./gradlew build dependencyCheckAnalyze

        # Upload the build artifacts for reuse in the Docker job
      - name: Upload build artifacts
        id: artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: build/libs/app-fat.jar
          retention-days: 1
          overwrite: true