name: 🔧 GitOps
run-name: ${{ github.actor }} is updating staging stack.
permissions:
  contents: write

on:
  workflow_call:
    inputs:
      app-img:
        required: true
        type: string

jobs:
  update-image-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
      # - name: Install yq
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y yq
      - name: Update image
        run: |
          yq e -i '.services.app.image = "${{ inputs.app-img }}"' gitops/staging/docker-compose.yaml
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add gitops/staging/docker-compose.yaml
          git commit -m "Updated gitops/staging/docker-compose.yaml"
          git push
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: gitops-staging